name: Deploy React App to AWS Amplify
on:
    workflow_dispatch:
        inputs:
            action:
                description: 'Terraform action to perform'
                type: choice
                options: 
                    - apply
                    - destroy

jobs: 
    terraform_apply:
        name: "Terraform Apply"
        if: ${{ github.event.inputs.action == 'apply' }}
        runs-on: ubuntu-latest
        env: 
            TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        steps:
            - name: Checkout repository-code
              uses: actions/checkout@v2
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1  

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.5.0

            - name: Terraform Init
              run: terraform init
              working-directory: terraform/

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve  
              working-directory: terraform/  

    terraform_destroy:
        name: "Terraform Destroy"
        if: ${{ github.event.inputs.action == 'destroy' }}
        runs-on: ubuntu-latest
        env: 
            TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        steps:
            - name: Checkout repository-code
              uses: actions/checkout@v2
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1  

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.5.0

            - name: Terraform Init
              run: terraform init
              working-directory: terraform/

            - name: Terraform Destroy
              if: github.ref == 'refs/heads/main'
              run: terraform destroy -auto-approve  
              working-directory: terraform/

